server:
  port: 8081
  servlet:
    context-path: /

#spring:
#  mvc:
#    view:
#      prefix: /
#      suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.rex.entity